# render.yaml - Infrastructure as Code for deploying the CMK Asistanı backend on Render.
# This blueprint defines a web service and a persistent disk for the vector store.

services:
  # A web service for our FastAPI application
  - type: web
    name: cmk-asistani-backend
    # Use the Python 3.11 environment
    env: python
    # This service will be deployed in the Frankfurt (EU) region.
    # Other options: oregon, ohio, singapore
    region: frankfurt
    # Define the branch to deploy from
    branch: main # Or master, depending on your default branch
    # Define the build command. This runs every time you push a new commit.
    # 1. Installs all Python packages from requirements.txt.
    # 2. Runs the ingestion script to create the chroma_db vector store on the persistent disk.
    buildCommand: |
      pip install -r requirements.txt
      python scripts/ingest.py
    # Define the command to start the web server.
    # Render provides the $PORT environment variable.
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    # Health check to ensure the service is running
    healthCheckPath: / 